### ISSUE TITLE
Dataset?

### ISSUE THREAD

**Issue by jyzhao** [ElMarmos/Bilgewater-Brawlers-Bay#24]
Hi, I'm doing a research about LoL too. I wonder if you are willing to share the dataset you collected? So that I save save the hazard downloading the dataset forever.

Thank you so much!

**Comment by ElMarmos** [comment]
Unfortunatly, we delete all the files we downloaded from riot servers because they were too heavy (16 Gb), but we can provide you a back up of the database we used in the Bilgewater App. You can find the database model in the "About" tab of the app and see if it works for you. You just make us know and we will send it to you ASAP. Best Regards!

**Comment by jyzhao** [comment]
Thank you so much!!!
It would be awesome if you can send the backup to jy.zhao@outlook.com
Thank you again for your help and I can't be more grateful for that.

I just need the data for NA region.
Thank you.
